export const types = {
    OPEN_SNACKBAR: 'OPEN_SNACKBAR',
    CLOSE_SNACKBAR: 'CLOSE_SNACKBAR',
    ADD_TO_CART: 'ADD_TO_CART',
    RESET_CART: 'RESET_CART',
    START_UPDATE_PRODUCTS: 'START_UPDATE_PRODUCTS',
    FINISH_UPDATE_PRODUCTS: 'FINISH_UPDATE_PRODUCTS',
    ERROR_UPDATE_PRODUCTS: 'ERROR_UPDATE_PRODUCTS',
};
